[tools]
chezmoi = "latest"
gh = "latest"
go = "latest"
jj = "latest"
neovim = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
zoxide = "latest"
eza = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
node = "lts"
yt-dlp = "latest"
yazi = "latest"
jq = "latest"
claude = "latest"
fastfetch = "latest"
"github:anomalyco/opencode" = "latest"

[env]
SUDO_EDITOR = "nvim"
EDITOR = "nvim"
VISUAL = "nvim"
BROWSER = "wslview"

